version: '3.6'

services:
  redis1:
    image: redis:5
    ports:
      - "7000:7000"
    volumes:
      - ./docker-data/redis-1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.2
  redis2:
    image: redis:5
    ports:
      - "7001:7001"
    volumes:
      - ./docker-data/redis-2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.3
  redis3:
    image: redis:5
    ports:
      - "7002:7002"
    volumes:
      - ./docker-data/redis-3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      app_net:
        ipv4_address: 173.17.0.4
  redis-cluster-setup:
    image: redis:5
    command: sh -c "
      sleep 5
      && yes yes | redis-cli
      --cluster create 173.17.0.2:7000 173.17.0.3:7001 173.17.0.4:7002
      --cluster-replicas 0
      && redis-cli --cluster check 173.17.0.2:7000"
    networks:
      app_net:
    depends_on:
      - redis1
      - redis2
      - redis3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16